<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-language" content="ja" />
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
    <base target="_self" />
	
	<!-- jQuery this is required -->
	<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.3.2.min.js'); ?>"></script>
    
	<?php echo $this->headLink(); ?>

</head> 
<body>
<?php echo $this->layout()->content ?>
</body>
</html>
